version: '3'

services:
  mysql-db:
    image: my-website-backend-image:latest
    container_name: my-website-backend-container
    ports:
      - "3306:3306"
    networks:
      - my_bridge_network
networks:
  my_bridge_network:
    driver: bridge